import React, { useState } from 'react';
import { ShoppingCart, Plus, Filter, Eye, CheckCircle, Clock, XCircle } from 'lucide-react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { usePage, Link } from '@inertiajs/react';
import CancelOrderModal from './CancelOrderModal';

const PartnerOrdersList = () => {
  const { auth, partnerOrders, partners } = usePage().props;

  const [filters, setFilters] = useState({
    status: '',
    partner_id: ''
  });

  const getStatusConfig = (status) => {
    const configs = {
      pending: {
        icon: Clock,
        color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
        label: 'Pending'
      },
      partially_fulfilled: {
        icon: CheckCircle,
        color: 'bg-blue-100 text-blue-800 border-blue-200',
        label: 'Partially Fulfilled'
      },
      fulfilled: {
        icon: CheckCircle,
        color: 'bg-green-100 text-green-800 border-green-200',
        label: 'Fulfilled'
      },
      cancelled: {
        icon: XCircle,
        color: 'bg-red-100 text-red-800 border-red-200',
        label: 'Cancelled'
      }
    };
    return configs[status] || configs.pending;
  };

  const isAutoGenerated = (order) => {
    const notes = (order.notes || '').toLowerCase();
    const contractNotes = (order.contract?.notes || '').toLowerCase();
    // Match any note that starts with or contains "auto-generated"
    return notes.includes('auto-generated') || contractNotes.includes('auto-generated');
  };

  const canCancel = (order) => {
    if (isAutoGenerated(order)) return false;
    return order.status === 'pending';
  };

  const filteredOrders = partnerOrders.data.filter(o => {
    if (filters.status && o.status !== filters.status) return false;
    if (filters.partner_id && o.partner?.id !== parseInt(filters.partner_id)) return false;
    return true;
  });

  const stats = {
    total: partnerOrders.data.length,
    pending: partnerOrders.data.filter(o => o.status === 'pending').length,
    partially: partnerOrders.data.filter(o => o.status === 'partially_fulfilled').length,
    fulfilled: partnerOrders.data.filter(o => o.status === 'fulfilled').length
  };


  const convertToKg = (qty, unit) => {
    if (unit === 'ton') return qty * 1000;
    if (unit === 'sack') return qty * 50;
    return qty; // kg, liter
  };

  const [cancelModal, setCancelModal] = useState({
    isOpen: false,
    order: null
  });

  const openCancelModal = (order) => {
    setCancelModal({ isOpen: true, order });
  };

  const closeCancelModal = () => {
    setCancelModal({ isOpen: false, order: null });
  };


  return (
    <AuthenticatedLayout
      user={auth.user}
      header={
        <h2 className="text-[25px] font-[800]" style={{ fontFamily: "'Poppins', sans-serif" }}>
          <span className="text-[#37692F] font-[800]">VIGOUR SEEDS</span>
          <span className="text-[#333333] font-[400]"> | Inventory Management</span>
        </h2>
      }
    >
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Partner Orders</h1>
              <p className="text-gray-600 mt-1">Manage seed and item deliveries to partners</p>
            </div>
            <Link
              href={route('partner-orders.create')}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition"
            >
              <Plus size={20} />
              New Order
            </Link>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
            <div className="bg-white rounded-lg shadow p-6 border-l-4 border-gray-500">
              <p className="text-gray-600 text-sm">Total Orders</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.total}</p>
            </div>
            <div className="bg-white rounded-lg shadow p-6 border-l-4 border-yellow-500">
              <p className="text-gray-600 text-sm">Pending</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.pending}</p>
            </div>
            <div className="bg-white rounded-lg shadow p-6 border-l-4 border-blue-500">
              <p className="text-gray-600 text-sm">Partially Fulfilled</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.partially}</p>
            </div>
            <div className="bg-white rounded-lg shadow p-6 border-l-4 border-green-500">
              <p className="text-gray-600 text-sm">Fulfilled</p>
              <p className="text-3xl font-bold text-gray-900 mt-1">{stats.fulfilled}</p>
            </div>
          </div>

          {/* Filters */}
          <div className="bg-white rounded-lg shadow p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <Filter size={20} className="text-gray-600" />
              <h3 className="font-semibold text-gray-900">Filters</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <select
                value={filters.status}
                onChange={(e) => setFilters({...filters, status: e.target.value})}
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="">All Status</option>
                <option value="pending">Pending</option>
                <option value="partially_fulfilled">Partially Fulfilled</option>
                <option value="fulfilled">Fulfilled</option>
                <option value="cancelled">Cancelled</option>
              </select>
              <select
                value={filters.partner_id}
                onChange={(e) => setFilters({...filters, partner_id: e.target.value})}
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option value="">All Partners</option>
                {partners.map(p => (
                  <option key={p.id} value={p.id}>{p.name}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Orders Table */}
          <div className="bg-white rounded-lg shadow overflow-hidden">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Order Details
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Partner
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Fulfillment
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Total Value
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredOrders.map((order) => {
                  const statusConfig = getStatusConfig(order.status);
                  const StatusIcon = statusConfig.icon;
                  const contractNumber = order.contract?.contract_number || '';
                  const fulfillment = order.fulfillment_percentage || 0;
                  const linesCount = order.lines?.length || 0;
                  const totalValue = order.lines?.reduce((sum, line) => {
                    let qty = Number(line.qty) || 0;
                    let price = Number(line.price_per_unit) || 0;
                    switch (line.unit) {
                      case 'sack':
                        qty = qty * 50;
                        break;
                      case 'ton':
                        qty = qty * 1000;
                        break;
                    }
                    return sum + (qty * price);
                  }, 0) || 0;

                  // Separate "Awaiting Stock" indicator for Pending orders only
                  let needsStock = false;
                  if (order.status === 'pending' && Array.isArray(order.lines)) {
                    needsStock = order.lines.some(line => {
                      const availableStockKg = line.product?.available_stock ?? 0;
                      const remainingQtyKg = convertToKg(
                        (Number(line.qty) || 0) - (Number(line.delivered_qty) || 0),
                        line.unit
                      );
                      return remainingQtyKg > availableStockKg;
                    });
                  }

                  return (
                    <tr key={order.id} className="hover:bg-gray-50 transition">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="bg-blue-100 p-2 rounded">
                            <ShoppingCart className="text-blue-600" size={20} />
                          </div>
                          <div>
                            <p className="font-medium text-gray-900">{order.order_number || `PO-${order.contract?.contract_name}-${order.id}`}</p>
                            <p className="text-sm text-gray-500">
                              {order.order_date
                                ? new Date(order.order_date).toLocaleString('en-GB', {
                                    year: 'numeric',
                                    month: '2-digit',
                                    day: '2-digit',
                                  }).replace(',', '')
                                : ''}
                            </p>
                            {contractNumber && (
                              <span className="text-xs bg-purple-100 text-purple-800 px-2 py-0.5 rounded mt-1 inline-block">
                                {contractNumber}
                              </span>
                            )}
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <p className="text-sm font-medium text-gray-900">{order.partner?.name}</p>
                        <p className="text-xs text-gray-500">{linesCount} line items</p>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <StatusIcon size={16} />
                          <span className={`px-3 py-1 text-xs font-medium rounded-full border ${statusConfig.color}`}>
                            {statusConfig.label}
                          </span>
                          {/* Separate Awaiting Stock badge for Pending orders with shortage */}
                          {order.status === 'pending' && needsStock && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full border bg-amber-100 text-amber-800 border-amber-200 ml-2">
                              <span role="img" aria-label="warning">⚠️</span> Awaiting Stock
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <div className="flex-1 bg-gray-200 rounded-full h-2">
                            <div
                              className={`h-2 rounded-full transition-all ${
                                fulfillment === 100 ? 'bg-green-600' : 
                                fulfillment > 0 ? 'bg-blue-600' : 'bg-gray-400'
                              }`}
                              style={{ width: `${fulfillment}%` }}
                            />
                          </div>
                          <span className="text-sm font-medium text-gray-700 w-12 text-right">
                            {Number(fulfillment).toFixed(2)}%
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="font-bold text-gray-900">
                          ₱{totalValue.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <Link
                          href={route('partner-orders.show', { partnerOrder: order.id })}
                          className="flex items-center gap-2 text-blue-600 hover:text-blue-800 font-medium text-sm transition"
                        >
                          <Eye size={16} />
                          View Details
                        </Link>
                        {/* Cancel button logic */}
                        {canCancel(order) && (
                          <button
                            onClick={() => openCancelModal(order)}
                            className="ml-3 text-red-600 hover:text-red-800 font-medium text-sm transition"
                          >
                            Cancel
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <CancelOrderModal
        isOpen={cancelModal.isOpen}
        onClose={closeCancelModal}
        order={cancelModal.order}
      />
    </AuthenticatedLayout>
  );
};

export default PartnerOrdersList;